#!/usr/bin/env node
// app.js — cPanel / Passenger entry point.
//
// cPanel's "Setup Node.js App" (Node.js Selector / Phusion Passenger) expects
// an `app.js` at the application root. Our actual Next.js server lives at
// `.next/standalone/server.js` and is generated by `npm run build` (because
// next.config has `output: 'standalone'`). This file is a thin wrapper that
// changes into the standalone directory and delegates to the real server.
//
// On a VPS / Docker, you don't need this file — use `node .next/standalone/server.js`
// directly. It's purely for cPanel compatibility.

const path = require("path");
const fs = require("fs");

const standaloneDir = path.join(__dirname, ".next", "standalone");
const serverPath = path.join(standaloneDir, "server.js");

if (!fs.existsSync(serverPath)) {
  console.error("❌  .next/standalone/server.js not found.");
  console.error("    Did you run `npm run build`?");
  console.error("    Looking at: " + serverPath);
  process.exit(1);
}

// The standalone server uses Node's relative module resolution from inside
// .next/standalone/ — chdir there so it finds its bundled dependencies the
// same way `node server.js` would when launched from that directory.
process.chdir(standaloneDir);

// HOSTNAME/PORT are picked up by the server. Passenger sets PORT automatically.
require(serverPath);
